image: rfc1149/rose-dev
services:
#  - postgres

before_script:
#  - bundle install

after_script:
#  - rm secrets

stages:
  - build
  - test
  - deploy

run_simple_test:
  stage: test
  script:
    - echo "this is a small example of continued integration."

build_spy:
  stage: build
  script:
    - cd spy_talk
    - make

build_stealth:
  stage: build
  script:
    - cd stealth_drop
    - make

build_lora_discovery:
  stage: build
  script:
    - cd lora_discovery
    - make

artifacts_flashable:
  stage: deploy
  artifacts:
    paths:
    - lora_discovery/main
    - spy_talk/_build/nrf52832_xxaa.hex
    - stealth_drop/main
    expire_in: 1 week

# Sample job
#job1:
#  stage: build
#  script:
#    - execute-script-for-job1
#  only:
#    - master
#  tags:
#    - docker
