image: rfc1149/rose-dev
services:
#  - postgres

before_script:
#  - bundle install

after_script:
#  - rm secrets

stages:
  - lint
  - build
  - test
  - deploy

run_simple_test:
  stage: test
  script:
    - echo "this is a small example of continued integration."

# LINT STAGE
# Uses smaller image for faster lint

lint_main:
  stage: lint
  image: alabate/clang-format
  script:
    - cd spy_talk
    - make format
    - cd ../stealth_drop
    - make format
    - cd ../lora_discovery
    - make format
    - git status --porcelain

lint_test:
  stage: lint
  image: alabate/clang-format
  script:
    - cd test
    - cd fibo
    - make format
    - git status --porcelain

# BUILD STAGE

build_spy:
  stage: build
  script:
    - cd spy_talk
    - make

build_stealth:
  stage: build
  script:
    - cd stealth_drop
    - make

build_lora_discovery:
  stage: build
  script:
    - cd lora_discovery
    - make

build_test:
  stage: build
  script:
    - cd test/fibo
    - make

# TEST STAGE

test_fibo:
  stage: test
  script:
    - cd test/fibo
    - ./main

# DEPLOY STAGE

artifacts_flashable:
  stage: deploy
  script:
  artifacts:
    paths:
    - lora_discovery/main
    - spy_talk/_build/nrf52832_xxaa.hex
    - stealth_drop/main
    expire_in: 1 week

# Sample job
#job1:
#  stage: build
#  script:
#    - execute-script-for-job1
#  only:
#    - master
#  tags:
#    - docker
