services:
#  - postgres

before_script:
#  - bundle install

after_script:
#  - rm secrets

stages:
  - lint
  - build
  - test
  - deploy

# LINT STAGE
# Use smaller image for faster lint

lint_main:
  stage: lint
  image: rfc1149/rose-dev
  script:
    - make format -C software/nRF52_ble_common
    - make format -C software/spy_talk
    - make format -C software/usb_sniffer/STM32
    - make format -C software/usb_sniffer/nRF52
    - git diff-index HEAD  # To help with problem identification
    - test $(git diff-index HEAD | wc -l) = 0

lint_apps:
  stage: lint
  image : lpzantony/sdk
  script:
    - export GRADLE_USER_HOME=$PWD/.gradle-cache
    - cd smartphone
    - cd BLEParrot
    - mkdir -p "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew lint
    - cd ../WifiParrot
    - ./gradlew lint
  tags:
    - android
  cache:
    key: android
    paths:
      - .gradle-cache
      - smartphone/BLEParrot/.gradle/
      - smartphone/WifiParrot/.gradle/

# BUILD STAGE

build_main:
  stage: build
  image: tuetuopay/arm-none-eabi
  script:
    - make -C software/nRF52_ble_common
    - make test_board -C software/spy_talk
    - make clean -C software/spy_talk
    - make -C software/spy_talk
    - make -C software/usb_sniffer/STM32
    - make -C software/usb_sniffer/nRF52
  artifacts:
    paths:
    - software/spy_talk/_build/nrf52832_xxaa.out
    - software/usb_sniffer/STM32/build/usb_sniffer.elf
    - software/usb_sniffer/nRF52/_build/nrf52832_xxaa.out
    expire_in: 1 week

build_apps:
  stage: build
  image : lpzantony/little-brosers
  script:
    - export GRADLE_USER_HOME=$PWD/.gradle-cache
    - cd smartphone
    - cd BLEParrot
    - mkdir "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew build
    - cd ../WifiParrot
    - ./gradlew build
  artifacts:
    paths:
    - smartphone/BLEParrot/app/build/outputs/apk/app-release-unsigned.apk
    - smartphone/BLEParrot/usbsniffer/build/outputs/apk/usbsniffer-release-unsigned.apk
    - smartphone/BLEParrot/spytalk/build/outputs/apk/spytalk-release-unsigned.apk
    - smartphone/WifiParrot/app/build/outputs/apk/app-release-unsigned.apk
    expire_in: 1 week
  tags:
    - android
  cache:
    key: android
    paths:
      - .gradle-cache
      - smartphone/BLEParrot/.gradle/
      - smartphone/WifiParrot/.gradle/

# TEST STAGE

# Runs all JUnit tests
test_apps:
  stage: test
  image : lpzantony/little-brosers
  script:
    - export GRADLE_USER_HOME=$PWD/.gradle-cache
    - cd smartphone
    - cd BLEParrot
    - mkdir -p "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew test
    - cd ../WifiParrot
    - ./gradlew test
  tags:
    - android
  cache:
    key: android
    paths:
      - .gradle-cache
      - smartphone/BLEParrot/.gradle/
      - smartphone/WifiParrot/.gradle/

# DEPLOY STAGE

# Sample job
#job1:
#  stage: build
#  script:
#    - execute-script-for-job1
#  only:
#    - master
#  tags:
#    - docker
