services:
#  - postgres

before_script:
#  - bundle install

after_script:
#  - rm secrets

stages:
  - lint
  - build
  - test
  - deploy

# LINT STAGE
# Use smaller image for faster lint

lint_main:
  stage: lint
  image: rfc1149/rose-dev
  script:
    - cd Training/BLE_nrf52
    - make format
    - cd ../../usb_dev_kit
    - make format
    - cd ../lora_dev_kit
    - make format
    - cd ../lora_discovery
    - make format
    - git status --porcelain

lint_apps:
  stage: lint
  image : runmymind/docker-android-sdk
  script:
    - cd smartphone
    - cd BLEParrot
    - ./gradlew lint

lint_test:
  stage: lint
  image: rfc1149/rose-dev
  script:
    - cd Training/Test
    - make format
    - git status --porcelain

# BUILD STAGE

build_main:
  stage: build
  image: tuetuopay/arm-none-eabi
  script:
    - cd Training/BLE_nrf52
    - make
    - cd ../../usb_dev_kit
    - make
    - cd ../lora_dev_kit
    - make
    - cd ../lora_discovery
    - make
  artifacts:
    paths:
    - lora_discovery/main
    - Training/BLE_nrf52/_build/nrf52832_xxaa.out
    - usb_dev_kit/build/usb_dev_kit.elf
    - lora_dev_kit/build/lora_dev_kit.elf
    expire_in: 1 week

build_apps:
  stage: build
  image : runmymind/docker-android-sdk
  script:
    - cd smartphone
    - cd BLEParrot
    - ./gradlew build
  artifacts:
    paths:
    - smartphone/BLEParrot/app/build/outputs/apk/app-release-unsigned.apk
    expire_in: 1 week

build_test:
  stage: build
  image: rfc1149/rose-dev
  script:
    - cd Training/Test
    - make
  artifacts:
    paths:
    - Training/Test/main
    expire_in: 20 minutes

# TEST STAGE

# Runs all JUnit tests
test_apps:
  stage: test
  image : runmymind/docker-android-sdk
  script:
    - cd smartphone
    - cd BLEParrot
    - ./gradlew test

test_test:
  stage: test
  image: rfc1149/rose-dev
  script:
    - cd Training/Test
    - ./main

# DEPLOY STAGE

# Sample job
#job1:
#  stage: build
#  script:
#    - execute-script-for-job1
#  only:
#    - master
#  tags:
#    - docker
