image: rfc1149/rose-dev
services:
#  - postgres

before_script:
#  - bundle install

after_script:
#  - rm secrets

stages:
  - lint
  - build
  - test
  - deploy

# LINT STAGE
# Use smaller image for faster lint

lint_main:
  stage: lint
#  image: alabate/clang-format
  script:
    - cd nrf52_dev_kit
    - make format
    - cd ../usb_dev_kit
    - make format
    - cd ../lora_discovery
    - make format
    - git status --porcelain

lint_test:
  stage: lint
#  image: alabate/clang-format
  script:
    - cd test
    - make format
    - git status --porcelain

# BUILD STAGE

build_main:
  stage: build
  script:
    - cd nrf52_dev_kit
    - make
    - cd ../usb_dev_kit
    - make
    - cd ../lora_discovery
    - make
  artifacts:
    paths:
    - lora_discovery/main
    - nrf52_dev_kit/_build/nrf52832_xxaa.hex
    - usb_dev_kit/build/usb_dev_kit.elf
    expire_in: 1 week

build_test:
  stage: build
  script:
    - cd test
    - make
  artifacts:
    paths:
    - test/main
    expire_in: 20 minutes

# TEST STAGE

test_test:
  stage: test
  script:
    - cd test
    - ./main

# DEPLOY STAGE

# Sample job
#job1:
#  stage: build
#  script:
#    - execute-script-for-job1
#  only:
#    - master
#  tags:
#    - docker
