services:
#  - postgres

before_script:
#  - bundle install

after_script:
#  - rm secrets

stages:
  - lint
  - build
  - test
  - deploy

# LINT STAGE
# Use smaller image for faster lint

lint_main:
  stage: lint
  image: rfc1149/rose-dev
  script:
    - cd Training/BLE_nrf52
    - make format
    - cd ../USB_keyboard
    - make format
    - cd ../lora_discovery
    - make format
    - cd ../WiFi
    - make format
    - cd ../LoRa_sx1276
    - make format
    - cd ../software/usb_sniffer/STM32
    - make format
    - git status --porcelain

lint_apps:
  stage: lint
  image : lpzantony/ndk
  script:
    - cd smartphone
    - cd BLEParrot
    - mkdir "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew lint
    - cd ../WifiParrot
    - ./gradlew lint
  tags:
    - android

lint_test:
  stage: lint
  image: rfc1149/rose-dev
  script:
    - cd Training/Test
    - make format
    - git status --porcelain

# BUILD STAGE

build_main:
  stage: build
  image: tuetuopay/arm-none-eabi
  script:
    - cd Training/BLE_nrf52
    - make
    - cd ../USB_keyboard
    - make
    - cd ../lora_discovery
    - make
    - cd ../WiFi
    - make
    - cd ../LoRa_sx1276
    - make
    - cd ../software/usb_sniffer/STM32
    - make
  artifacts:
    paths:
    - Training/BLE_nrf52/_build/nrf52832_xxaa.out
    - Training/USB_keyboard/build/USB_keyboard.elf
    - Training/LoRa_sx1276/_build/nrf52832_xxaa.out
    - Training/WiFi/build/wifi_dev_kit.elf
    - software/usb_sniffer/STM32/build/usb_sniffer.elf
    expire_in: 1 week

build_apps:
  stage: build
  image : lpzantony/little-brosers
  script:
    - cd smartphone
    - cd BLEParrot
    - mkdir "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew build
    - cd ../WifiParrot
    - ./gradlew build
  artifacts:
    paths:
    - smartphone/BLEParrot/app/build/outputs/apk/app-release-unsigned.apk
    - smartphone/WifiParrot/app/build/outputs/apk/app-release-unsigned.apk
    expire_in: 1 week
  tags:
    - android

build_test:
  stage: build
  image: rfc1149/rose-dev
  script:
    - cd Training/Test
    - make
  artifacts:
    paths:
    - Training/Test/main
    expire_in: 20 minutes

# TEST STAGE

# Runs all JUnit tests
test_apps:
  stage: test
  image : lpzantony/little-brosers
  script:
    - cd smartphone
    - cd BLEParrot
    - mkdir "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew test
    - cd ../WifiParrot
    - ./gradlew test
  tags:
    - android

test_test:
  stage: test
  image: rfc1149/rose-dev
  script:
    - cd Training/Test
    - ./main

# DEPLOY STAGE

# Sample job
#job1:
#  stage: build
#  script:
#    - execute-script-for-job1
#  only:
#    - master
#  tags:
#    - docker
