services:
#  - postgres

before_script:
#  - bundle install

after_script:
#  - rm secrets

stages:
  - lint
  - build
  - test
  - deploy

# LINT STAGE
# Use smaller image for faster lint

lint_main:
  stage: lint
  image: rfc1149/rose-dev
  script:
    - make format -C Training/BLE_nrf52
    - make format -C Training/USB_keyboard
    - make format -C Training/lora_discovery
    - make format -C Training/LoRa_sx1276
    - make format -C Training/WiFi
    - make format -C software/usb_sniffer/STM32
    - git status --porcelain

lint_apps:
  stage: lint
  image : lpzantony/ndk
  script:
    - export GRADLE_USER_HOME=$PWD/.gradle-cache
    - cd smartphone
    - cd BLEParrot
    - mkdir -p "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew lint
    - cd ../WifiParrot
    - ./gradlew lint
  tags:
    - android
  cache:
    key: android
    paths:
      - .gradle-cache
      - smartphone/BLEParrot/.gradle/
      - smartphone/WifiParrot/.gradle/

# BUILD STAGE

build_main:
  stage: build
  image: tuetuopay/arm-none-eabi
  script:
    - make -C Training/BLE_nrf52
    - make -C Training/USB_keyboard
    - make -C Training/lora_discovery
    - make test_board -C Training/LoRa_sx1276
    - make clean -C Training/LoRa_sx1276
    - make -C Training/LoRa_sx1276
    - make -C Training/WiFi
    - make -C software/usb_sniffer/STM32
  artifacts:
    paths:
    - Training/BLE_nrf52/_build/nrf52832_xxaa.out
    - Training/USB_keyboard/build/USB_keyboard.elf
    - Training/LoRa_sx1276/_build/nrf52832_xxaa.out
    - Training/WiFi/build/wifi_dev_kit.elf
    - software/usb_sniffer/STM32/build/usb_sniffer.elf
    expire_in: 1 week

build_apps:
  stage: build
  image : lpzantony/little-brosers
  script:
    - export GRADLE_USER_HOME=$PWD/.gradle-cache
    - cd smartphone
    - cd BLEParrot
    - mkdir "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew build
    - cd ../WifiParrot
    - ./gradlew build
  artifacts:
    paths:
    - smartphone/BLEParrot/app/build/outputs/apk/app-release-unsigned.apk
    - smartphone/WifiParrot/app/build/outputs/apk/app-release-unsigned.apk
    expire_in: 1 week
  tags:
    - android
  cache:
    key: android
    paths:
      - .gradle-cache
      - smartphone/BLEParrot/.gradle/
      - smartphone/WifiParrot/.gradle/

# TEST STAGE

# Runs all JUnit tests
test_apps:
  stage: test
  image : lpzantony/little-brosers
  script:
    - export GRADLE_USER_HOME=$PWD/.gradle-cache
    - cd smartphone
    - cd BLEParrot
    - mkdir -p "$ANDROID_HOME/licenses" && cp ../android-sdk-license "$ANDROID_HOME/licenses"
    - ./gradlew test
    - cd ../WifiParrot
    - ./gradlew test
  tags:
    - android
  cache:
    key: android
    paths:
      - .gradle-cache
      - smartphone/BLEParrot/.gradle/
      - smartphone/WifiParrot/.gradle/

# DEPLOY STAGE

# Sample job
#job1:
#  stage: build
#  script:
#    - execute-script-for-job1
#  only:
#    - master
#  tags:
#    - docker
